# Семинар 1. Инструменты: Python, Numpy

Данный семинар будет посвящен основным инструментам анализа данных.

План ноутбука:
* Очень кратко вспомнить азы Python и порешать легкие задачи
* Порешать задачи в контексте библиотеки Numpy
* Если успеем, начать крутить данные при помощи Pandas

В то время как многие из Вас почувствуют некоторую скуку при виде темы данного семинара, остальные могут почувствовать ужас и страх перед неизвестным. В случае, если после семинара у Вас осталось ощущение, что Вы не готовы, отбросьте сомнения и немного потренируйтесь на предоставленных дополнительных материалах и/или любых открытых платформах в интернете (тысячи их), навык написания кода на питоне нарабатывается крайне быстро.

### Основные инструменты, с которыми вы столкнетесь в рамках данного курса

* [Colab](https://colab.research.google.com/#scrollTo=-Rh3-Vt9Nev9)  -  на основной странице есть несколько полезных подсказок
* [Google](https://www.google.com/) & [StackOverflow](https://stackoverflow.com/) - тут вы знаете, что делать :) Просьба не слепо копировать ответы, а **перепечатывать** код и **понимать**, что в нём происходит.
* [NumPy](https://numpy.org/doc/stable/user/) - посмотрите *quickstart* & *basics*, *array creation* и *indexing* тоже важны.
* [Pandas](https://pandas.pydata.org/docs/user_guide/) - полное описание фичей пандаса. Просто ищите нужный функционал и вычитывайте, как оно работает, если у вас не получаеся что-то сделать.
* [Matplotlib](https://matplotlib.org/stable/tutorials/index.html) & [Plotly](https://plotly.com/python/) - основные графически библиотеки. В большинстве случаев, вам хватит базового туториала + ответов с stackoverflow/google.
* [Seaborn](https://seaborn.pydata.org/tutorial/introduction.html) - надстройка над Matplotlib, в целом позволяет делать очень приятные графики.
* [Scikit-learn](https://scikit-learn.org/stable/user_guide.html) - маст-хэв библиотека любого начинающего датасаентиста и ученого. Отлично подходит для проведения исследований и обучения, но не годится к использованию в индустрии. Внутри есть юзергайд и большое количество туториалов по различным ML аспектам.
* [Pytorch](https://pytorch.org/tutorials/beginner/basics/intro.html) - основная библиотека для работы с нейронными сетями.


Форма для анонимных отзывов: появится :)

$ a = 1 $
текст

In [1]:
a = 1

# Домашнее задание 1

Первое домашнее задание будет заключаться в сдаче данного ноутбука со всеми выполненными заданиями. В сданном ноутбуке должны быть сделаны как и семинарские задания, так и задания с пометкой (HW).

**Дедлайн: 16е сентября (понедельник), 19.30**

Для идентификации автора работы, пожалуйста:

* (HW) Укажите в данной ячейке ваше ФИО:
* (HW) Заполните данную анкету: TODO

## 1. Python

Содержание:
* Списки
* Словари
* Условия
* Циклы
* Функции

Вспомним несколько фактов:

* В Python присваивание переменной значения не создает копию объекта. Вместо этого, переменная просто становится ссылкой на этот объект.

* В Python есть изменяемые и неизменяемые типы. Изменяемые отличаются тем, что их содержимое можно сменить, не изменив ссылку на них. Неизменяемые объекты приходится пересоздавать, чтобы отразить изменения состояния. При этом все старые ссылки не видят это обновление, потому что указывают на старый объект.

In [7]:
a = [1, 2, 3]

In [8]:
b = a

In [9]:
b

[1, 2, 3]

In [10]:
a.append(4)

In [11]:
b

[1, 2, 3, 4]

## Списки

Первый объект нашего интереса - списки, или, как их еще называют, листы.

Список - это упорядоченная изменяемая (mutable) коллекция объектов произвольных типов.

In [12]:
l1 = [1, 2, '3', 'word', ['word', 8, 14]]

Список - изменяемый объект. Убедимся, что это так.

In [14]:
l2 = l1
print(l1, l2, id(l1), id(l2), sep='\n')

[1, 2, '3', 'word', ['word', 8, 14]]
[1, 2, '3', 'word', ['word', 8, 14]]
131984865403904
131984865403904


In [15]:
l1.pop()

['word', 8, 14]

In [16]:
print(l1, l2, id(l1), id(l2), sep='\n')

[1, 2, '3', 'word']
[1, 2, '3', 'word']
131984865403904
131984865403904


Потренируемся работать со списками, предварительно задав выборку чисел в списке `items`.

In [17]:
items = [5, -24, 76, 44, 4, -16, 57, 0, -11,
         98, 13, 80, 16, 30, -27, -21, 78, 72]

In [20]:
items[0]

5

**Задача 0**

Найдите произведение первого и последнего элементов списка `items`.

In [27]:
items[0] * items[-1]

360

In [26]:
items[-55]

IndexError: list index out of range

**Задача 1**

Найди частное суммы первых трех элементов, начиная со второго и суммы последних двух элементов.

In [29]:
sum(items[1:4])

96

In [30]:
s1 = items[1:4]
s2 = items[-2:]
sum(s1) / sum(s2)

0.64

**Задача 2**

Найди размах выборки (разницу между максимальным и минимальным элементами).

In [31]:
items

[5, -24, 76, 44, 4, -16, 57, 0, -11, 98, 13, 80, 16, 30, -27, -21, 78, 72]

In [33]:
min(items)

-27

In [35]:
abs(min(items) - max(items))

125

**Задача 3**

Найди среднее значение выборки.

In [36]:
sum(items) / len(items)

26.333333333333332

**Задача 4 (HW)**

Найдите медиану.

**Задача 5 (HW)**

Удалите третье значение и найдите медиану.

**Задача 6 (HW)**

Возведите каждый элемент списка в квадрат.

## Словари

In [37]:
type([1,2,3])

list

In [39]:
{1: [1,2,3], 1: [1,2]}

{1: [1, 2]}

In [42]:
items = {3: -2,
         4: 'value1',
         22: 2,
         10: 1.22}

**Задача 1**

Добавьте в словарик по ключу `1` значение `-20`

In [41]:
b = [1,2,3]
b.append(4)
b

[1, 2, 3, 4]

In [44]:
items[1] = -20

In [45]:
items

{3: -2, 4: 'value1', 22: 2, 10: 1.22, 1: -20}

**Задача 2**

Какое значение лежит в словаре по самому маленькому ключу?

In [48]:
items.items()

dict_items([(3, -2), (4, 'value1'), (22, 2), (10, 1.22), (1, -20)])

In [47]:
items.values()

dict_values([-2, 'value1', 2, 1.22, -20])

In [46]:
items.keys()

dict_keys([3, 4, 22, 10, 1])

In [49]:
min(items.keys())

1

In [50]:
items[min(items.keys())]

-20

**Задача 3**

Удалите ключ из задачи 2 и заново решите её.

In [51]:
items.pop(1)

-20

In [53]:
min(items.keys())

3

In [52]:
items[min(items.keys())]

-2

In [54]:
dict_1 = {1: 10, 2: 20}
dict_2 = {3: 30, 4: 40}
dict_3 = {3: 50, 6: 60}

**Задача 4**

Объедините три словаря в один.

In [56]:
dict_1.update(dict_2)

In [58]:
dict_1.update(dict_3)
dict_1

{1: 10, 2: 20, 3: 50, 4: 40, 6: 60}

**Задача 5**

Замените все значения словаря на их квадраты.

## Условия

Синтаксис:
```
if условие:
    что делать, если оно выполнено
elif условие:
    что делать, если оно выполнено
else:
    что делать, если не выполнилось ни одно условие выше
```
Всё, что происходит внутри условия, отделяется отступом.

**Задача 1**

Заведите переменную year и проверьте, является ли введеный год високосным.

Год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [64]:
year = 2020

if year % 4 == 0 and year % 100 != 0:
  print('Високосный')
elif year % 400 == 0:
  print('Високосный')
else:
  print('Обычный')

Високосный


## Циклы

In [ ]:
while tmp != 0:
  ...
  tmp -= 1

Синтаксис:
```
for i in диапазон_изменений_i:
    команды
```
Все, что происходит внутри цикла, отделяется отступом.

**Задача 1**

Напиши программу для вывода картинки заданной глубины (используйте вложенные циклы).
```
*
**
***
****
*****
****
***
**
*
```

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ твой код

## Функции

Синтаксис:

```
def название функции(список аргументов):
    команды
    return результат выполнения функции
```

То, что происходит внутри функции отделяется отступом.

In [ ]:
def hello(name, surname='Иванов'):

**Задача 1**

Напишите функцию, принимающую на вход строку, и разворачивающую её вспять.

In [ ]:
def inverse(s:str) -> str:
  ...

**Задача 2 (HW)**

Напишите функцию, которая принимает на вход число n, числа a, b и генерирует случайных числе с отрезка от $a$ до $b$.

In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ твой код

## 2. Numpy

В задачах анализа данных часто используются многомерные массивы. В частности, выборка обычно имеет вид матрицы размера
$N \times d$, где
$N$ — количество объектов, а
$d$ — признаков.

Но чистый Python довольно неудобный и слишком медленный для подобных задач. Конечно, можно представить матрицу в виде «списка списков», но с первого раза без ошибок такой объект сложно даже создать. Например, так делать не надо:

In [65]:
vector = [0, 0, 0, 0, 0]  # Создаём строчку
matrix = 5 * [vector]     # Создаём список из строчек
matrix

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [66]:
matrix[0][0] = 1  # Хотим изменить один элемент
matrix            # А получилось что-то не то...

[[1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0]]

Но даже если мы сможем корректно создать матрицу в виде списка списков, функции для работы с ней придётся писать самостоятельно. Они будут содержать циклы языка Python и, как следствие, медленно работать.

Поэтому естественно было придумать библиотеку для работы с многомерными массивами. Такой библиотекой стала библиотека NumPy.

NumPy — библиотека языка Python, позволяющая удобно работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении.

## Основной класс - `ndarray`

Основной класс в `numpy` - `ndarray`, многомерный массив.

`ndarray` имеет все преимущества массива, а также обеспечивает быструю обработку без использования относительно медленных циклов Python.

Каждый подобный массив имеет несколько измерений или осей — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси и т.д.

## Импорт `numpy`

`import numpy as np`

`np` - синоним имени модуля, пространство имен, ссылка для доступа к компонентам модуля


In [67]:
import numpy as np

## Способы создания массива

- `np.array(obj, dtype, ...)` - преобразование из списка, кортежа, генератора, другого массива, ...
    - `obj` - объект, который нужно преобразовать
    - `dtype` - тип элемента массива
- функции `numpy`
- операции с массивами

In [68]:
# одномерный массив из списка и кортежа
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [69]:
# получили объект типа numpy.ndarray
type(x)

numpy.ndarray

In [72]:
for i in range(13):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12


In [70]:
# преобразование из генератора
np.array(range(13))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
# преобразование из генератора списка
np.array([x**2 for x in range(13)])

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

## Типы элементов массива

В отличие от чистого Python`а с динамической типизацией в NumPy типизация статическая, как в C/C++. Поэтому у каждого многомерного массива должен быть тип элементов, который обычно можно указать явно с помощью параметра dtype. К тому же, все элементы в массиве должны быть одного типа.

Встроенные типы `Python`:

- `int`, `bool`, `float`, `complex`, `str`, ...

Типы `numpy`:

- `np.int0`, `np.int8`, `np.int16`, `np.int32`, `np.int64`
- `np.float`, `np.float16`, `np.float32`, `np.float64`
- `np.complex`, `np.complex64`, `np.complex128`

Также можно задать тип, эквивалентный `struct` в языке Си, т.е. упорядоченный набор из разнотипных элементов, занимающих жестко фиксированное количество байт.


Здесь без явного указания массив будет состоять из целых чисел:

In [74]:
np.array([[1, 2, 3], [1, 2, 3]], dtype=float)

array([[1., 2., 3.],
       [1., 2., 3.]])

Доступна и бóльшая экзотика. Например, можно потребовать, чтобы массив состоял из 16-битных чисел с плавающей точкой. Но в курсе нам будет достаточно простых типов int, float, bool.

In [75]:
np.array([[1, 2, 3], [1, 2, 3]], dtype=np.float16)

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float16)

Ещё можно создавать массив определённого размера из нулей:

In [76]:
arr = np.zeros((3, 4), dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

... единиц:

In [77]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

... вообще из чего угодно:



In [78]:
np.full((3, 4), 5, dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

... а память просто выделять, не инициализируя:

In [79]:
np.empty((5, 4))

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

In [80]:
# массив с элементами разных типов
for dtype in (int, float, bool):
    print('%r' % np.array([0, 1, 2, 3], dtype=dtype))

array([0, 1, 2, 3])
array([0., 1., 2., 3.])
array([False,  True,  True,  True])


In [81]:
# массив с элементами разных типов
for dtype in (np.int0, np.int8, np.int16, np.int32):
    arr = np.array([0, 1, 2, 3], dtype=dtype)
    print(dtype)
    print('%r' % arr)
    print('memory size:', arr.nbytes, end='\n'*2)

<class 'numpy.int64'>
array([0, 1, 2, 3])
memory size: 32

<class 'numpy.int8'>
array([0, 1, 2, 3], dtype=int8)
memory size: 4

<class 'numpy.int16'>
array([0, 1, 2, 3], dtype=int16)
memory size: 8

<class 'numpy.int32'>
array([0, 1, 2, 3], dtype=int32)
memory size: 16



<ipython-input-81-31ce702e982f>:2: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  for dtype in (np.int0, np.int8, np.int16, np.int32):


## Атрибуты массива

- `arr.shape` - размеры массива = его форма (кортеж)
- `arr.size` - количество элементов массива
- `arr.dtype` - тип элемента массива
- `arr.ndim` - количество измерений массива (целое число > 0)
- `arr.strides` - шаги в байтах для перехода к следующему элементу измерения (кортеж)
- `arr.nbytes` - размер занимаемой памяти в байтах

In [82]:
arr = np.array(range(12))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
arr.ndim, arr.size, arr.dtype, arr.shape, arr.strides, arr.nbytes

(1, 12, dtype('int64'), (12,), (8,), 96)

Изменять «размерность» массива можно с помощью метода reshape. Для этого, конечно, произведение размерностей должно равняться количеству элементов массива.

In [88]:
arr = arr.reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Вместо количества элементов по одной «размерности» можно указать -1, и тогда NumPy сам посчитает это число:

In [89]:
arr = arr.reshape(4, -1)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Ещё одна полезная функция — np.arange(...), которая по сути эквивалентна запуску np.array(range(...)).

Полученный одномерный массив удобно превращать в матрицу с помощью reshape:

In [90]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

К тому же, можно генерировать матрицы из вероятностных распределений.

Вот матрица размера $3 \times 4$ из $\mathcal{N}(0,10)$:

In [91]:
np.random.normal(0, np.sqrt(10), (3, 4))

array([[ 0.99227948,  0.02679473,  9.33148704, -3.59295203],
       [-0.71283148, -2.45207896, -2.56377464,  3.51006714],
       [-4.04890276, -1.52636615,  3.47772214, -5.30978698]])

**Задание 1 (HW)**

Создать массивы типа `ndarray` и вывести на экран:
- содержимое
- форму
- размер занимаемой памяти

1. одномерный массив, содержащий действительные числа $\pi, \frac{\pi}{2}, \frac{\pi}{4}, \frac{\pi}{9}, \frac{\pi}{16}, ..., \frac{\pi}{1024}$

2. одномерный массив, содержащий константу `True`, если число делится на 5, иначе - `False` для чисел 10, ..., 100.


In [ ]:
### ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ твой код

**Задание 2 (HW)**
1. Сгенерировать последовательность из 100 элементов: `[1.18, 3.27, ...]`

2. Создать двумерный массив из 100 псевдослучайных чисел, равномерно распределенных на полуинтервале $[\pi, 10\pi)$

3. Преобразовать полученный массив так, чтобы элементы стали целочисленными

4. Из массива `[0, 1, ..., 99]` случайным образом выбрать 10 элементов


**Задание 3 (HW)**

Реализуйте функцию, принимающую на вход массив целых неотрицательных чисел `nums` и возвращающую самый частый элемент массива.

In [ ]:
def most_frequent(nums):
    """
    Find the most frequent value in an array
    :param nums: array of ints
    :return: the most frequent value
    """
    pass # your code here